arch: s390x
services:
  - docker
script: docker login quay.io -u $ROBOT_USER -p $ROBOT_TOKEN && docker build Elasticsearch --tag quay.io/ibmz/elasticsearch:7.9.1 && docker push quay.io/ibmz/elasticsearch:7.9.1
